language: python
python: 3.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-format-5.0
      - xsltproc

install:
  - python -m pip install -r requirements.txt

jobs:
  include:
    - name: "Python Tests"
      script:
        - git clone -b interchange https://github.com/Xilinx/RapidWright.git
        - git clone https://github.com/capnproto/capnproto-java.git
        - CAPNP_PATH=$(pwd)/capnproto-java/compiler/src/main/schema/ INTERCHANGE_SCHEMA_PATH=$(pwd)/RapidWright/interchange make test-py
    - name: "Check Formatting"
      script:
        - make format
        - test $(git status --porcelain | wc -l) -eq 0 || { git diff; false; }
    - name: "License Checks"
      script:
        - ./.github/check_license.sh
        - ./.github/check_python_scripts.sh
