name: CI tests

on: [push, pull_request]

jobs:

  Run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8']
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install clang-format-5.0 xsltproc git
        pip install --upgrade -r requirements.txt

    - name: Check formatting
      run: ./.github/workflows/format.sh

    - name: Get and build tools
      run: |
        make build
        git clone -b interchange https://github.com/Xilinx/RapidWright.git $GITHUB_WORKSPACE/RapidWright
        make -C "$GITHUB_WORKSPACE/RapidWright" update_jars
        git clone https://github.com/capnproto/capnproto-java.git $GITHUB_WORKSPACE/capnproto-java

    - name: Test
      run: ./.github/workflows/test.sh

    - name: "License Checks"
      run: |
        ./.github/check_license.sh
        ./.github/check_python_scripts.sh
